### ISSUE TITLE
Wraparound when resampling on Raspbian armhf

### ISSUE THREAD

**Issue by drigz** [xiph/speexdsp#13]
I found that when resampling from 16k to 48k on the Raspberry Pi 3, libspeex sometimes introduces very bad distortion. I originally discovered this with ALSA's rate_speexrate plugin, but it occurs when libspeexdsp directly too. The installed version is libspeexdsp1-1.2~rc1.2-1 from Raspbian Jessie. The issue is not present on x86_64.

Here is the source code for a test case:
[speex-resampler.tar.gz](https://github.com/xiph/speexdsp/files/1105307/speex-resampler.tar.gz)

```
sudo apt-get install sox libspeexdsp-dev
tar xf speex-resampler.tar.gz
cd speex-resampler
make
aplay test_48k.wav
```

This is what the waveform looks like before and after resampling:

![image](https://user-images.githubusercontent.com/632207/27588317-1175349a-5b48-11e7-9260-bd9600b669d0.png)

**Comment by jmvalin** [comment]
The reason it's only on ARM is likely because of fixed-point. It'd be good to check whether the generic fixed-point also has the bug or just the Neon version.

**Comment by drigz** [comment]
Could you explain how I could test the generic fixed version?

Am 30.06.2017 10:55 nachm. schrieb "Jean-Marc Valin" <
notifications@github.com>:

**Comment by tmatth** [comment]
On Tue, Jul 4, 2017 at 2:45 AM, Rodrigo Queiro <notifications@github.com>
wrote:

> Could you explain how I could test the generic fixed version?
>
> Am 30.06.2017 10:55 nachm. schrieb "Jean-Marc Valin" <
> notifications@github.com>:
>
> > The reason it's only on ARM is likely because of fixed-point. It'd be
> good
> > to check whether the generic fixed-point also has the bug or just the
> Neon
> > version.
>

Try ./configure --enable-fixed-point --disable-neon

**Comment by tmatth** [comment]
And thanks for the detailed report, I will try on a NEON device.

**Comment by fbarchard** [comment]
The smlal in ARM does a 16 bit * 16 bit multiple and accumulate to 32 bit, but does not clamp.
I made the 64 bit code do exactly what the 32 bit NEON code does.
What does the C and/or x86 do?

**Comment by tmatth** [comment]
@drigz So I can reproduce this with the packaged speexdsp on Rasbpian as well, however so far I can't with the latest speexdsp.

**Comment by tmatth** [comment]
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=799176
