### ISSUE TITLE
Error at ./configure step

### ISSUE THREAD

**Issue by TranBaNgoc** [xiph/speexdsp#31]
Hello every one! I get an error at this step, it's:
./configure: line 10227: syntax error near unexpected token `FFT,'
./configure: line 10227: `  PKG_CHECK_MODULES(FFT, fftw3f)'
Help me, please!

**Comment by StuartIanNaylor** [comment]
./configure: line 10227: syntax error near unexpected token `FFT,'
./configure: line 10227: `  PKG_CHECK_MODULES(FFT, fftw3f)'

Same preinstalled speex, speexdsp and dev libs and every fft3w lib I could find.
On Raspbian 32bit it installs but Aaarch64 always get the above error on ./configure

**Comment by rillian** [comment]
This sounds like the `PKG_CHECK_MODULES` macro wasn't expanded properly. It's defined in /usr/share/aclocal/pkg.m4. Do you have `pkg-config`installed on your system?

**Comment by StuartIanNaylor** [comment]
Many thanks you got it.

So sudo apt-get install autotools-dev autoconf libtool
Don't `--enable-neon`

Then you are ready to roll :)

**Comment by StuartIanNaylor** [comment]
@rillian Apols as I willingly admit I know little about compiling and often get stuck :)

Your indo solved the previous problems and wondering if you could just give a little bit more info on the gpl_fftw option.
What linker options do you need to specify if using gpl-options?

Really would like to try just to see if there is any optimisation benefit tried a few guesses but so far failed as getting errors from the speexdsp lib that the fftw linkers are unknown?

**Comment by zh794390558** [comment]
install `pkg-config`

**Comment by tmatth** [comment]
Closing since the issue was that @TranBaNgoc was missing pkg-config. For reference we do have CI running defined here:
https://gitlab.xiph.org/xiph/speexdsp/-/blob/master/.gitlab-ci.yml

that is run for every commit.
