### ISSUE TITLE
port resample_neon.h to aarch64

### ISSUE THREAD

**Issue by fbarchard** [xiph/speexdsp#7]
resample_neon.h is inline assembly for armv7 32 bit NEON.
To compile this for aarch64, the functions need a port.  The file contains 4 functions.
saturate_32bit_to_16bit()
inner_product_single(int16_t *a,...)
saturate_float_to_16bit()
inner_product_single(float *a,...)

resample.c includes the neon using a macro:
# ifdef _USE_NEON
# include "resample_neon.h"
# endif

which needs to be set in the makefile.

Attached is a patch
[resample_neon.txt](https://github.com/xiph/speexdsp/files/377077/resample_neon.txt)

**Comment by fbarchard** [comment]
pushed a fix into a fork and a pull request https://github.com/xiph/speexdsp/pull/8

**Comment by fbarchard** [comment]
Anyone able to take the get pull request or apply the patch above?

**Comment by tmatth** [comment]
Fixed in #8
