### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by nijikon** [xiph/speexdsp#9]
With the recent release of speex 1.2.0, are you planning to release speexdsp 1.2.0 any time soon?

**Comment by tmatth** [comment]
Probably not until at least https://github.com/xiph/speexdsp/pull/8 has been reviewed and merged, and I wouldn't mind adding some checkasm code as well.

**Comment by MarioG-X** [comment]
I also need speexdsp, freeswitch no longer builds on macOS since speex 1.2.0.

**Comment by tmatth** [comment]
Hi,

The latest release of SpeexDSP is available at https://ftp.osuosl.org/pub/xiph/releases/speex/speexdsp-1.2.0.tar.gz
